# Generated by Django 5.0.4 on 2024-04-06 16:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=55)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('duration', models.IntegerField()),
                ('university_building', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5)])),
                ('description', models.TextField(max_length=1200)),
                ('faculty', models.CharField(choices=[('FCAD', 'Faculty of Computer-Aided Design'), ('FITC', 'Faculty of Information Technologies and Control'), ('MF', 'Military Faculty'), ('FRE', 'Faculty of Radioengineering and Electronics'), ('FCSN', 'Faculty of Computer Systems and Networks'), ('FIS', 'Faculty of Information Security'), ('FEE', 'Faculty of Engineering and Economics'), ('TUC', 'Trade Union Committee')], max_length=50)),
                ('date_time_post', models.DateTimeField()),
            ],
        ),
    ]
